name: BOOK STORE CI

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
        env:
          MONGODB_CNN: ${{ secrets.MONGODB_CNN }}
          PORT: ${{ secrets.PORT }}
